// ════════════════════════════════════════
// receipt.js — Receipt Preview & Export
// CHANGED: Added shareWhatsApp() for
//          WhatsApp text summary share.
// ════════════════════════════════════════

async function buildReceipt(vid) {
  const v = (await gVis()).find(x => x.id === vid);
  if (!v) return '<p>Not found</p>';

  const p   = (await gPts()).find(x => x.id === v.patientId) || {};
  const s   = await gSet();
  const rno = vid.replace('v_', '').slice(-6);

  return `<div class="rw" id="r-${vid}">
    <div class="rh">
      <div style="display:flex;align-items:flex-start;gap:10px">
        ${s.logo ? `<img src="${s.logo}" style="width:48px;height:48px;object-fit:contain;border-radius:8px;flex-shrink:0;border:1px solid var(--bd);padding:2px"/>` : ''}
        <div>
          <div class="rb">${s.businessName || 'MediAssist Pro'}<span>${s.tagline || 'Home Medical Care'}</span></div>
          <div style="font-size:13px;color:var(--tx2);margin-top:5px">${s.name} · ${s.rank}</div>
          ${s.phone   ? `<div style="font-size:12px;color:var(--tx3)">${s.phone}</div>`   : ''}
          ${s.address ? `<div style="font-size:12px;color:var(--tx3)">${s.address}</div>` : ''}
        </div>
      </div>
      <div class="rm">
        <div style="font-weight:700;font-size:14px">RECEIPT</div>
        <div>#${rno}</div>
        <div>${fmtDate(v.date)}</div>
        <div>${v.time || ''}</div>
      </div>
    </div>

    <div class="rp">
      <strong>${p.name || v.patientName}</strong>
      ${[p.age ? p.age + ' yrs' : '', p.gender, p.phone].filter(Boolean).join(' · ')}
      ${p.address ? `<div style="font-size:12px;color:var(--tx2)">${p.address}</div>` : ''}
    </div>

    ${v.notes ? `<div style="font-size:13px;color:var(--tx2);margin-bottom:10px"><strong>Notes:</strong> ${v.notes}</div>` : ''}

    <table class="rtbl">
      <thead><tr><th>#</th><th>Service</th><th style="text-align:right">Rs.</th></tr></thead>
      <tbody>
        ${v.services.map((svc, i) =>
          `<tr><td>${i + 1}</td><td>${svc.name}</td><td style="text-align:right">${(svc.price || 0).toLocaleString()}</td></tr>`
        ).join('')}
      </tbody>
    </table>

    <div style="display:flex;flex-direction:column;align-items:flex-end;gap:5px;margin-bottom:9px;font-size:14px">
      <div>Subtotal: <strong>Rs. ${(v.subtotal || 0).toLocaleString()}</strong></div>
      ${v.discount ? `<div style="color:var(--err)">Discount: - Rs. ${v.discount.toLocaleString()}</div>` : ''}
    </div>

    <div class="rtot">
      <span>Total Payable</span>
      <span style="color:var(--ok)">Rs. ${(v.net || 0).toLocaleString()}</span>
    </div>

    <div class="rfoot">
      Thank you for trusting us with your care. Get well soon!<br>Generated by MediAssist Pro
    </div>
  </div>`;
}

async function previewReceipt(vid) {
  document.getElementById('rcptContent').innerHTML   = await buildReceipt(vid);
  document.getElementById('rcptContent').dataset.vid = vid;
  openMo('rcptModal');
}

async function saveImage() {
  const el = document.getElementById('rcptContent');
  const canvas = await html2canvas(el, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
  canvas.toBlob(blob => {
    const url = URL.createObjectURL(blob);
    const a   = document.createElement('a');
    a.href = url; a.download = 'Receipt_' + Date.now() + '.jpg';
    a.click();
    URL.revokeObjectURL(url);
    toast('Receipt saved to device!');
  }, 'image/jpeg', 0.95);
}

/**
 * ADDED: Share a plain-text receipt summary via WhatsApp.
 * Opens wa.me with a pre-filled message — works on both
 * mobile (opens WhatsApp app) and desktop (opens web).
 */
async function shareWhatsApp() {
  const vid = document.getElementById('rcptContent').dataset.vid;
  if (!vid) return;

  const v   = (await gVis()).find(x => x.id === vid);
  if (!v)   return;
  const s   = await gSet();
  const p   = (await gPts()).find(x => x.id === v.patientId) || {};
  const rno = vid.replace('v_', '').slice(-6);

  const serviceLines = (v.services || [])
    .map(svc => `  • ${svc.name} — Rs. ${(svc.price || 0).toLocaleString()}`)
    .join('\n');

  const discountLine = v.discount
    ? `\nDiscount:  -Rs. ${v.discount.toLocaleString()}`
    : '';

  const text = [
    `🏥 *${s.businessName || 'MediAssist Pro'}*`,
    s.tagline ? `_${s.tagline}_` : '',
    '',
    `📋 *Receipt #${rno}*`,
    `📅 ${fmtDate(v.date)}${v.time ? '  ' + v.time : ''}`,
    '',
    `👤 *Patient:* ${v.patientName}`,
    '',
    `*Services:*`,
    serviceLines,
    '',
    `Subtotal:  Rs. ${(v.subtotal || 0).toLocaleString()}${discountLine}`,
    `*Total:    Rs. ${(v.net || 0).toLocaleString()}*`,
    '',
    s.phone   ? `📞 ${s.phone}`   : '',
    s.address ? `📍 ${s.address}` : '',
    '',
    '_Sent via MediAssist Pro_',
  ].filter(l => l !== null).join('\n').replace(/\n{3,}/g, '\n\n').trim();

  // Patient E.164 phone (same pattern as buildWhatsAppURL)
  const digits = (p.phone || '').replace(/\D/g, '');
  const e164   = digits
    ? digits.startsWith('92')
      ? digits
      : digits.startsWith('0')
        ? '92' + digits.slice(1)
        : '92' + digits
    : '';

  // Capture image then share
  const el = document.getElementById('rcptContent');
  const canvas = await html2canvas(el, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
  const blob = await new Promise(r => canvas.toBlob(r, 'image/jpeg', 0.95));

  // Web Share API — image + text (works on mobile Chrome/WhatsApp)
  if (navigator.share) {
    try {
      const file = new File([blob], 'Receipt_' + Date.now() + '.jpg', { type: 'image/jpeg' });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ files: [file], text: text, title: 'Receipt' });
        return;
      }
    } catch (_) { /* fall through */ }
  }

  // Fallback: save image to device + open WhatsApp text
  const url = URL.createObjectURL(blob);
  const a   = document.createElement('a');
  a.href = url; a.download = 'Receipt_' + Date.now() + '.jpg'; a.click();
  URL.revokeObjectURL(url);
  toast('Receipt image saved!');

  const wa = e164
    ? 'https://wa.me/' + e164 + '?text=' + encodeURIComponent(text)
    : 'https://wa.me/?text=' + encodeURIComponent(text);
  window.open(wa, '_blank', 'noopener');
}
